# Generated by Django 5.2.17 on 2026-09-11 12:43

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="file",
            field=models.FileField(
                upload_to="attachments/", validators=[core.models.validate_file_size]
            ),
        ),
    ]
