# Generated by Django 5.2.17 on 2026-09-11 12:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_attachment_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="step_entered_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
