# Generated by Django 5.2.17 on 2026-09-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_request_step_entered_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="on_hold_from_step",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DRAFT", "Draft"),
                    ("SUBMITTED", "Submitted"),
                    ("TESTING", "Testing"),
                    ("APPROVAL", "Approval"),
                    ("DEPLOYMENT", "Deployment"),
                    ("LIVE", "Live"),
                    ("REJECTED", "Rejected"),
                    ("ON_HOLD", "On Hold"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
