# Generated by Django 5.2.17 on 2026-09-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_request_on_hold_from_step"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="on_hold_reason",
            field=models.TextField(blank=True),
        ),
    ]
