# Generated by Django 5.2.17 on 2026-09-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_request_on_hold_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="on_hold_from_step",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="request",
            name="on_hold_reason",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
